# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-karpenter-node-pool
  description: This component deploys [Karpenter NodePools](https://karpenter
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
